### ISSUE TITLE
Resource 'replacements.properties' not loaded when natively compiled on GraalVM

### ISSUE THREAD

**Issue by simbo1905** [slugify/slugify#74]
I understand that this will be a little esoteric to this project but I wanted to document the problem and hopefully find a fix for others. At this repo https://github.com/simbo1905/realworld-api-quarkus on the develop branch if I run:

```
./mvnw clean package -Dmaven.test.skip=true -Dquarkus.package.type=legacy-jar
docker-compose up --build
```

then in another consoler test it with: 

```
./collections/run-api-tests.sh
```

Everything runs okay. 

So to be clear there is no problem when running the the code as a normal Java-as-bytecode sort of application. 

If I then natively ahead-of-time compile for Java 17 with GraalVM 21.3.0 with: 

```
./native-build.sh
docker-compose -f docker-compose-native.yml up --build
```

*WARNING* that ahead-of-time compile build maxes out my new mac book for several minutes and needs me to allocate 4cpu and 5G to docker so it is a bit  of hard work

Then run the tests with: 

```
./collections/run-api-tests.sh
```

I then get an error: 

```
realworld_1  | 2021-12-28 23:12:42,703 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /api/articles failed, error id: 95ac587a-643d-46a9-9047-66d29afc11b4-1: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Resource 'replacements.properties' not loaded!
realworld_1  | 	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
realworld_1  | 	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
realworld_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
realworld_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
realworld_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
realworld_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
realworld_1  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
realworld_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
realworld_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
realworld_1  | 	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
realworld_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
realworld_1  | 	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
realworld_1  | 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
realworld_1  | 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
realworld_1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
realworld_1  | 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
realworld_1  | 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
realworld_1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
realworld_1  | 	at java.lang.Thread.run(Thread.java:833)
realworld_1  | 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
realworld_1  | 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
realworld_1  | Caused by: java.lang.RuntimeException: Resource 'replacements.properties' not loaded!
realworld_1  | 	at com.github.slugify.Slugify.loadReplacements(Slugify.java:132)
realworld_1  | 	at com.github.slugify.Slugify.<init>(Slugify.java:44)
realworld_1  | 	at org.example.realworldapi.infrastructure.configuration.ApplicationConfiguration.slugify(ApplicationConfiguration.java:20)
realworld_1  | 	at org.example.realworldapi.infrastructure.configuration.ApplicationConfiguration_ProducerMethod_slugify_64f03cd2e6d3180824c900e19abf9fb340c3d82e_Bean.create(Unknown Source)
realworld_1  | 	at org.example.realworldapi.infrastructure.configuration.ApplicationConfiguration_ProducerMethod_slugify_64f03cd2e6d3180824c900e19abf9fb340c3d82e_Bean.create(Unknown Source)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
realworld_1  | 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
realworld_1  | 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
realworld_1  | 	at org.example.realworldapi.infrastructure.configuration.ApplicationConfiguration_ProducerMethod_slugify_64f03cd2e6d3180824c900e19abf9fb340c3d82e_Bean.get(Unknown Source)
realworld_1  | 	at org.example.realworldapi.infrastructure.configuration.ApplicationConfiguration_ProducerMethod_slugify_64f03cd2e6d3180824c900e19abf9fb340c3d82e_Bean.get(Unknown Source)
realworld_1  | 	at org.example.realworldapi.infrastructure.provider.SlugifySlugProvider_Bean.create(Unknown Source)
realworld_1  | 	at org.example.realworldapi.infrastructure.provider.SlugifySlugProvider_Bean.create(Unknown Source)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
realworld_1  | 	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
realworld_1  | 	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
realworld_1  | 	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
realworld_1  | 	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:18)
realworld_1  | 	at org.example.realworldapi.infrastructure.provider.SlugifySlugProvider_ClientProxy.arc$delegate(Unknown Source)
realworld_1  | 	at org.example.realworldapi.infrastructure.provider.SlugifySlugProvider_ClientProxy.slugify(Unknown Source)
realworld_1  | 	at org.example.realworldapi.domain.feature.impl.CreateSlugByTitleImpl.handle(CreateSlugByTitleImpl.java:18)
realworld_1  | 	at org.example.realworldapi.domain.feature.impl.CreateArticleImpl.handle(CreateArticleImpl.java:26)
realworld_1  | 	at org.example.realworldapi.application.web.resource.ArticlesResource.create(ArticlesResource.java:101)
realworld_1  | 	at org.example.realworldapi.application.web.resource.ArticlesResource_Subclass.create$$superforward1(Unknown Source)
realworld_1  | 	at org.example.realworldapi.application.web.resource.ArticlesResource_Subclass$$function$$1.apply(Unknown Source)
realworld_1  | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
realworld_1  | 	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:68)
realworld_1  | 	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor.validateMethodInvocation(JaxrsEndPointValidationInterceptor.java:35)
realworld_1  | 	at io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor_Bean.intercept(Unknown Source)
realworld_1  | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
realworld_1  | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
realworld_1  | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
realworld_1  | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
realworld_1  | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
realworld_1  | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
realworld_1  | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
realworld_1  | 	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
realworld_1  | 	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
realworld_1  | 	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
realworld_1  | 	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
realworld_1  | 	at org.example.realworldapi.application.web.resource.ArticlesResource_Subclass.create(Unknown Source)
realworld_1  | 	at java.lang.reflect.Method.invoke(Method.java:568)
realworld_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
realworld_1  | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
realworld_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
realworld_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
realworld_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
realworld_1  | 	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
realworld_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
realworld_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
realworld_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
realworld_1  | 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
realworld_1  | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
realworld_1  | 	... 17 more
realworld_1  | Caused by: java.lang.NullPointerException: inStream parameter is null
realworld_1  | 	at java.util.Objects.requireNonNull(Objects.java:233)
realworld_1  | 	at java.util.Properties.load(Properties.java:407)
realworld_1  | 	at com.github.slugify.Slugify.loadReplacements(Slugify.java:128)
realworld_1  | 	... 73 more
```

The file `replacements.properties` is a classpath resource inside of `slugify-2.4.jar` and GraalVM doesn't include resource by default. The documentation for this is at https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/Resources.md and if using Quarkus it is covered at https://quarkus.io/guides/writing-native-applications-tips#including-resources 

Those instructions do not have a way to have GraalVM load the resource from inside `slugify-2.4.jar` rather the `replacements.properties` has to be extracted into the source tree and the native compile options setup to embed the file into the final native image.

**Comment by simbo1905** [comment]
Okay in my case the fix was to unzip the `replacements.properties` from `slugify-2.4.jar` into my maven `src\main\resources` then I have a `src\main\resources\resources-config.json` that has: 

```
{
  "resources": [
    {
      "pattern": ".*\\.xml$"
    },
    {
      "pattern": ".*\\.json$"
    },
    {
      "pattern": ".*\\.properties$"
    }
  ]
}
```

The final pattern ensures that `replacements.properties` will be put into the native image. Quarkus is then told to use the json file with the following entry it `src\main\resources\application.properties`:

```
quarkus.native.additional-build-args=-H:ResourceConfigurationFiles=resources-config.json
```

That flag is then passed into GraalVM and things work. 

The catch with this approach is that if I bump the version of slugify I will not automatically update the `replacements.properties` file. I could update my build config to extract the file each time yet my automated tests all work so I may not get around to that.
